export const CURRANCIES_FETCHING = 'CURRANCIES_FETCHING';
export const ADD_CURRANCIES = 'ADD_CURRANCIES';
export const CURRANCIES_SET_ERRORS = 'CURRANCIES_SET_ERRORS';
export const CURRANCIES_SET_SUCCESS = 'CURRANCIES_SET_SUCCESS';